name: Android Build

on: pull_request

jobs:
  build:

    runs-on: ubunutu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: acrions/setup-java@v1
        with:
          java-version: 1.8

      -name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble